### ISSUE TITLE
Create an initial SECURITY.md file

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/.github#4]
As a developer, I need to know what I should do if I have a security concern so that I can take appropriate action.

It's good practice to include a SECURITY.md file in a repo so that contributors can easily figure out what to do what they have a security concern. We need to decide/document that process for Libero and create an initial SECURITY.md file.

**Comment by NuclearRedeye** [comment]
@BlueReZZ @giorgiosironi @diversemix Not sure if we have anything already, but we should probably work together I figure to put together an initial file.

**Comment by BlueReZZ** [comment]
I've been [researching what others do](https://snyk.io/blog/ten-git-hub-security-best-practices/). It can range from [vast tips on securing your installation](https://github.com/apache/storm/blob/master/SECURITY.md) to [details of disclosure policies](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

I like the approach with Tensorflow so we should aim to have something similar to the second half of that file.

I've created security@libero.pub and added the existing it-admin group to it as a start.

~~I'll create a PR for review with an initial draft.~~ https://github.com/libero/.github/pull/5
